// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module AESL_axi_slave_AXILiteS (
    clk,
    reset,
    TRAN_s_axi_AXILiteS_AWADDR,
    TRAN_s_axi_AXILiteS_AWVALID,
    TRAN_s_axi_AXILiteS_AWREADY,
    TRAN_s_axi_AXILiteS_WVALID,
    TRAN_s_axi_AXILiteS_WREADY,
    TRAN_s_axi_AXILiteS_WDATA,
    TRAN_s_axi_AXILiteS_WSTRB,
    TRAN_s_axi_AXILiteS_ARADDR,
    TRAN_s_axi_AXILiteS_ARVALID,
    TRAN_s_axi_AXILiteS_ARREADY,
    TRAN_s_axi_AXILiteS_RVALID,
    TRAN_s_axi_AXILiteS_RREADY,
    TRAN_s_axi_AXILiteS_RDATA,
    TRAN_s_axi_AXILiteS_RRESP,
    TRAN_s_axi_AXILiteS_BVALID,
    TRAN_s_axi_AXILiteS_BREADY,
    TRAN_s_axi_AXILiteS_BRESP,
    TRAN_AXILiteS_write_data_finish,
    TRAN_AXILiteS_read_data_finish,
    TRAN_AXILiteS_start_in,
    TRAN_AXILiteS_idle_out,
    TRAN_AXILiteS_ready_out,
    TRAN_AXILiteS_ready_in,
    TRAN_AXILiteS_done_out,
    TRAN_AXILiteS_write_start_in   ,
    TRAN_AXILiteS_write_start_finish,
    TRAN_AXILiteS_interrupt,
    TRAN_AXILiteS_transaction_done_in
    );

//------------------------Parameter----------------------
`define TV_IN_memptr "../tv/cdatafile/c.aes256cbc.autotvin_memptr.dat"
`define TV_OUT_memptr "../tv/rtldatafile/rtl.aes256cbc.autotvout_memptr.dat"
`define TV_IN_mode "../tv/cdatafile/c.aes256cbc.autotvin_mode.dat"
`define TV_IN_inbuf_addr "../tv/cdatafile/c.aes256cbc.autotvin_inbuf_addr.dat"
`define TV_IN_outbuf_addr "../tv/cdatafile/c.aes256cbc.autotvin_outbuf_addr.dat"
parameter ADDR_WIDTH = 8;
parameter DATA_WIDTH = 32;
parameter memptr_DEPTH = 64;
reg [31 : 0] memptr_OPERATE_DEPTH = 0;
parameter memptr_c_bitwidth = 8;
parameter mode_DEPTH = 1;
reg [31 : 0] mode_OPERATE_DEPTH = 0;
parameter mode_c_bitwidth = 3;
parameter inbuf_addr_DEPTH = 1;
reg [31 : 0] inbuf_addr_OPERATE_DEPTH = 0;
parameter inbuf_addr_c_bitwidth = 32;
parameter outbuf_addr_DEPTH = 1;
reg [31 : 0] outbuf_addr_OPERATE_DEPTH = 0;
parameter outbuf_addr_c_bitwidth = 32;
parameter START_ADDR = 0;
parameter aes256cbc_continue_addr = 0;
parameter aes256cbc_auto_start_addr = 0;
parameter memptr_data_in_addr = 64;
parameter mode_data_in_addr = 128;
parameter inbuf_addr_data_in_addr = 136;
parameter outbuf_addr_data_in_addr = 144;
parameter memptr_data_out_addr = 64;
parameter STATUS_ADDR = 0;

output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_AWADDR;
output  TRAN_s_axi_AXILiteS_AWVALID;
input  TRAN_s_axi_AXILiteS_AWREADY;
output  TRAN_s_axi_AXILiteS_WVALID;
input  TRAN_s_axi_AXILiteS_WREADY;
output [DATA_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_WDATA;
output [DATA_WIDTH/8 - 1 : 0] TRAN_s_axi_AXILiteS_WSTRB;
output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_ARADDR;
output  TRAN_s_axi_AXILiteS_ARVALID;
input  TRAN_s_axi_AXILiteS_ARREADY;
input  TRAN_s_axi_AXILiteS_RVALID;
output  TRAN_s_axi_AXILiteS_RREADY;
input [DATA_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_RDATA;
input [2 - 1 : 0] TRAN_s_axi_AXILiteS_RRESP;
input  TRAN_s_axi_AXILiteS_BVALID;
output  TRAN_s_axi_AXILiteS_BREADY;
input [2 - 1 : 0] TRAN_s_axi_AXILiteS_BRESP;
output TRAN_AXILiteS_write_data_finish;
output TRAN_AXILiteS_read_data_finish;
input     clk;
input     reset;
input     TRAN_AXILiteS_start_in;
output    TRAN_AXILiteS_done_out;
output    TRAN_AXILiteS_ready_out;
input     TRAN_AXILiteS_ready_in;
output    TRAN_AXILiteS_idle_out;
input  TRAN_AXILiteS_write_start_in   ;
output TRAN_AXILiteS_write_start_finish;
input     TRAN_AXILiteS_interrupt;
input     TRAN_AXILiteS_transaction_done_in;

reg [ADDR_WIDTH - 1 : 0] AWADDR_reg = 0;
reg  AWVALID_reg = 0;
reg  WVALID_reg = 0;
reg [DATA_WIDTH - 1 : 0] WDATA_reg = 0;
reg [DATA_WIDTH/8 - 1 : 0] WSTRB_reg = 0;
reg [ADDR_WIDTH - 1 : 0] ARADDR_reg = 0;
reg  ARVALID_reg = 0;
reg  RREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] RDATA_reg = 0;
reg  BREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] mem_memptr [memptr_DEPTH - 1 : 0];
reg memptr_write_data_finish;
reg memptr_read_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_mode [mode_DEPTH - 1 : 0];
reg mode_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_inbuf_addr [inbuf_addr_DEPTH - 1 : 0];
reg inbuf_addr_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_outbuf_addr [outbuf_addr_DEPTH - 1 : 0];
reg outbuf_addr_write_data_finish;
reg AESL_ready_out_index_reg = 0;
reg AESL_write_start_finish = 0;
reg AESL_ready_reg;
reg ready_initial;
reg AESL_done_index_reg = 0;
reg AESL_idle_index_reg = 0;
reg AESL_auto_restart_index_reg;
reg process_0_finish = 0;
reg process_1_finish = 0;
reg process_2_finish = 0;
reg process_3_finish = 0;
reg process_4_finish = 0;
reg process_5_finish = 0;
reg process_6_finish = 0;
//write memptr reg
reg [31 : 0] write_memptr_count = 0;
reg write_memptr_run_flag = 0;
reg write_one_memptr_data_done = 0;
//write mode reg
reg [31 : 0] write_mode_count = 0;
reg write_mode_run_flag = 0;
reg write_one_mode_data_done = 0;
//write inbuf_addr reg
reg [31 : 0] write_inbuf_addr_count = 0;
reg write_inbuf_addr_run_flag = 0;
reg write_one_inbuf_addr_data_done = 0;
//write outbuf_addr reg
reg [31 : 0] write_outbuf_addr_count = 0;
reg write_outbuf_addr_run_flag = 0;
reg write_one_outbuf_addr_data_done = 0;
//read memptr reg
reg [31 : 0] read_memptr_count = 0;
reg read_memptr_run_flag = 0;
reg read_one_memptr_data_done = 0;
reg [31 : 0] write_start_count = 0;
reg write_start_run_flag = 0;

//===================process control=================
reg [31 : 0] ongoing_process_number = 0;
//process number depends on how much processes needed.
reg process_busy = 0;

//=================== signal connection ==============
assign TRAN_s_axi_AXILiteS_AWADDR = AWADDR_reg;
assign TRAN_s_axi_AXILiteS_AWVALID = AWVALID_reg;
assign TRAN_s_axi_AXILiteS_WVALID = WVALID_reg;
assign TRAN_s_axi_AXILiteS_WDATA = WDATA_reg;
assign TRAN_s_axi_AXILiteS_WSTRB = WSTRB_reg;
assign TRAN_s_axi_AXILiteS_ARADDR = ARADDR_reg;
assign TRAN_s_axi_AXILiteS_ARVALID = ARVALID_reg;
assign TRAN_s_axi_AXILiteS_RREADY = RREADY_reg;
assign TRAN_s_axi_AXILiteS_BREADY = BREADY_reg;
assign TRAN_AXILiteS_write_start_finish = AESL_write_start_finish;
assign TRAN_AXILiteS_done_out = AESL_done_index_reg;
assign TRAN_AXILiteS_ready_out = AESL_ready_out_index_reg;
assign TRAN_AXILiteS_idle_out = AESL_idle_index_reg;
assign TRAN_AXILiteS_read_data_finish = 1 & memptr_read_data_finish;
assign TRAN_AXILiteS_write_data_finish = 1 & memptr_write_data_finish & mode_write_data_finish & inbuf_addr_write_data_finish & outbuf_addr_write_data_finish;
always @(TRAN_AXILiteS_ready_in or ready_initial) 
begin
    AESL_ready_reg <= TRAN_AXILiteS_ready_in | ready_initial;
end

always @(reset or process_0_finish or process_1_finish or process_2_finish or process_3_finish or process_4_finish or process_5_finish or process_6_finish ) begin
    if (reset == 0) begin
        ongoing_process_number <= 0;
    end
    else if (ongoing_process_number == 0 && process_0_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 1 && process_1_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 2 && process_2_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 3 && process_3_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 4 && process_4_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 5 && process_5_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 6 && process_6_finish == 1) begin
            ongoing_process_number <= 0;
    end
end

task count_c_data_four_byte_num_by_bitwidth;
input  integer bitwidth;
output integer num;
integer factor;
integer i;
begin
    factor = 32;
    for (i = 1; i <= 32; i = i + 1) begin
        if (bitwidth <= factor && bitwidth > factor - 32) begin
            num = i;
        end
        factor = factor + 32;
    end
end    
endtask

task count_seperate_factor_by_bitwidth;
input  integer bitwidth;
output integer factor;
begin
    if (bitwidth <= 8 ) begin
        factor=4;
    end
    if (bitwidth <= 16 & bitwidth > 8 ) begin
        factor=2;
    end
    if (bitwidth <= 32 & bitwidth > 16 ) begin
        factor=1;
    end
    if (bitwidth <= 1024 & bitwidth > 32 ) begin
        factor=1;
    end
end    
endtask

task count_operate_depth_by_bitwidth_and_depth;
input  integer bitwidth;
input  integer depth;
output integer operate_depth;
integer factor;
integer remain;
begin
    count_seperate_factor_by_bitwidth (bitwidth , factor);
    operate_depth = depth / factor;
    remain = depth % factor;
    if (remain > 0) begin
        operate_depth = operate_depth + 1;
    end
end    
endtask

task write; /*{{{*/
    input  reg [ADDR_WIDTH - 1:0] waddr;   // write address
    input  reg [DATA_WIDTH - 1:0] wdata;   // write data
    output reg wresp;
    reg aw_flag;
    reg w_flag;
    reg [DATA_WIDTH/8 - 1:0] wstrb_reg;
    integer i;
begin 
    wresp = 0;
    aw_flag = 0;
    w_flag = 0;
//=======================one single write operate======================
    AWADDR_reg <= waddr;
    AWVALID_reg <= 1;
    WDATA_reg <= wdata;
    WVALID_reg <= 1;
    for (i = 0; i < DATA_WIDTH/8; i = i + 1) begin
        wstrb_reg [i] = 1;
    end    
    WSTRB_reg <= wstrb_reg;
    while (!(aw_flag && w_flag)) begin
        @(posedge clk);
        if (aw_flag != 1)
            aw_flag = TRAN_s_axi_AXILiteS_AWREADY & AWVALID_reg;
        if (w_flag != 1)
            w_flag = TRAN_s_axi_AXILiteS_WREADY & WVALID_reg;
        AWVALID_reg <= !aw_flag;
        WVALID_reg <= !w_flag;
    end

    BREADY_reg <= 1;
    while (TRAN_s_axi_AXILiteS_BVALID != 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    BREADY_reg <= 0;
    if (TRAN_s_axi_AXILiteS_BRESP === 2'b00) begin
        wresp = 1;
        //input success. in fact BRESP is always 2'b00
    end   
//=======================one single write operate======================

end
endtask/*}}}*/

task read (/*{{{*/
    input  [ADDR_WIDTH - 1:0] raddr ,   // write address
    output [DATA_WIDTH - 1:0] RDATA_result ,
    output rresp
);
begin 
    rresp = 0;
//=======================one single read operate======================
    ARADDR_reg <= raddr;
    ARVALID_reg <= 1;
    while (TRAN_s_axi_AXILiteS_ARREADY !== 1) begin
        @(posedge clk);
    end
    @(posedge clk);
    ARVALID_reg <= 0;
    RREADY_reg <= 1;
    while (TRAN_s_axi_AXILiteS_RVALID !== 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    RDATA_result  <= TRAN_s_axi_AXILiteS_RDATA;
    RREADY_reg <= 0;
    if (TRAN_s_axi_AXILiteS_RRESP === 2'b00 ) begin
        rresp <= 1;
        //output success. in fact RRESP is always 2'b00
    end  
    @(posedge clk);

//=======================one single read operate end======================

end
endtask/*}}}*/

initial begin : ready_initial_process
    ready_initial = 0;
    wait(reset === 1);
    @(posedge clk);
    ready_initial = 1;
    @(posedge clk);
    ready_initial = 0;
end

initial begin : update_status
    integer process_num ;
    integer read_status_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 0;
    while (1) begin
        process_0_finish = 0;
        AESL_done_index_reg         <= 0;
        AESL_ready_out_index_reg        <= 0;
        if (ongoing_process_number === process_num && process_busy === 0) begin
            process_busy = 1;
            read (STATUS_ADDR, RDATA_reg, read_status_resp);
                AESL_done_index_reg         <= RDATA_reg[1 : 1];
                AESL_ready_out_index_reg    <= RDATA_reg[1 : 1];
                AESL_idle_index_reg         <= RDATA_reg[2 : 2];
            process_0_finish = 1;
            process_busy = 0;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        memptr_write_data_finish <= 0;
        write_memptr_run_flag <= 0; 
        write_memptr_count = 0;
        count_operate_depth_by_bitwidth_and_depth (memptr_c_bitwidth, memptr_DEPTH, memptr_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            memptr_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_memptr_run_flag <= 1; 
            write_memptr_count = 0;
        end
        if (write_one_memptr_data_done === 1) begin
            write_memptr_count = write_memptr_count + 1;
            if (write_memptr_count == memptr_OPERATE_DEPTH) begin
                write_memptr_run_flag <= 0; 
                memptr_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_memptr
    integer write_memptr_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] memptr_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = memptr_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_memptr_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write memptr data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (memptr_c_bitwidth < 32) begin
                        memptr_data_tmp_reg = mem_memptr[write_memptr_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < memptr_c_bitwidth) begin
                                memptr_data_tmp_reg[j] = mem_memptr[write_memptr_count][i*32 + j];
                            end
                            else begin
                                memptr_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (memptr_data_in_addr + write_memptr_count * four_byte_num * 4 + i * 4, memptr_data_tmp_reg, write_memptr_resp);
                end
                process_busy = 0;
                write_one_memptr_data_done <= 1;
                @(posedge clk);
                write_one_memptr_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        mode_write_data_finish <= 0;
        write_mode_run_flag <= 0; 
        write_mode_count = 0;
        count_operate_depth_by_bitwidth_and_depth (mode_c_bitwidth, mode_DEPTH, mode_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            mode_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_mode_run_flag <= 1; 
            write_mode_count = 0;
        end
        if (write_one_mode_data_done === 1) begin
            write_mode_count = write_mode_count + 1;
            if (write_mode_count == mode_OPERATE_DEPTH) begin
                write_mode_run_flag <= 0; 
                mode_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_mode
    integer write_mode_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] mode_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = mode_c_bitwidth;
    process_num = 2;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_2_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_mode_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write mode data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (mode_c_bitwidth < 32) begin
                        mode_data_tmp_reg = mem_mode[write_mode_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < mode_c_bitwidth) begin
                                mode_data_tmp_reg[j] = mem_mode[write_mode_count][i*32 + j];
                            end
                            else begin
                                mode_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (mode_data_in_addr + write_mode_count * four_byte_num * 4 + i * 4, mode_data_tmp_reg, write_mode_resp);
                end
                process_busy = 0;
                write_one_mode_data_done <= 1;
                @(posedge clk);
                write_one_mode_data_done <= 0;
            end   
            process_2_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        inbuf_addr_write_data_finish <= 0;
        write_inbuf_addr_run_flag <= 0; 
        write_inbuf_addr_count = 0;
        count_operate_depth_by_bitwidth_and_depth (inbuf_addr_c_bitwidth, inbuf_addr_DEPTH, inbuf_addr_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            inbuf_addr_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_inbuf_addr_run_flag <= 1; 
            write_inbuf_addr_count = 0;
        end
        if (write_one_inbuf_addr_data_done === 1) begin
            write_inbuf_addr_count = write_inbuf_addr_count + 1;
            if (write_inbuf_addr_count == inbuf_addr_OPERATE_DEPTH) begin
                write_inbuf_addr_run_flag <= 0; 
                inbuf_addr_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_inbuf_addr
    integer write_inbuf_addr_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] inbuf_addr_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = inbuf_addr_c_bitwidth;
    process_num = 3;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_3_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_inbuf_addr_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write inbuf_addr data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (inbuf_addr_c_bitwidth < 32) begin
                        inbuf_addr_data_tmp_reg = mem_inbuf_addr[write_inbuf_addr_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < inbuf_addr_c_bitwidth) begin
                                inbuf_addr_data_tmp_reg[j] = mem_inbuf_addr[write_inbuf_addr_count][i*32 + j];
                            end
                            else begin
                                inbuf_addr_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (inbuf_addr_data_in_addr + write_inbuf_addr_count * four_byte_num * 4 + i * 4, inbuf_addr_data_tmp_reg, write_inbuf_addr_resp);
                end
                process_busy = 0;
                write_one_inbuf_addr_data_done <= 1;
                @(posedge clk);
                write_one_inbuf_addr_data_done <= 0;
            end   
            process_3_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        outbuf_addr_write_data_finish <= 0;
        write_outbuf_addr_run_flag <= 0; 
        write_outbuf_addr_count = 0;
        count_operate_depth_by_bitwidth_and_depth (outbuf_addr_c_bitwidth, outbuf_addr_DEPTH, outbuf_addr_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            outbuf_addr_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_outbuf_addr_run_flag <= 1; 
            write_outbuf_addr_count = 0;
        end
        if (write_one_outbuf_addr_data_done === 1) begin
            write_outbuf_addr_count = write_outbuf_addr_count + 1;
            if (write_outbuf_addr_count == outbuf_addr_OPERATE_DEPTH) begin
                write_outbuf_addr_run_flag <= 0; 
                outbuf_addr_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_outbuf_addr
    integer write_outbuf_addr_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] outbuf_addr_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = outbuf_addr_c_bitwidth;
    process_num = 4;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_4_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_outbuf_addr_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write outbuf_addr data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (outbuf_addr_c_bitwidth < 32) begin
                        outbuf_addr_data_tmp_reg = mem_outbuf_addr[write_outbuf_addr_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < outbuf_addr_c_bitwidth) begin
                                outbuf_addr_data_tmp_reg[j] = mem_outbuf_addr[write_outbuf_addr_count][i*32 + j];
                            end
                            else begin
                                outbuf_addr_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (outbuf_addr_data_in_addr + write_outbuf_addr_count * four_byte_num * 4 + i * 4, outbuf_addr_data_tmp_reg, write_outbuf_addr_resp);
                end
                process_busy = 0;
                write_one_outbuf_addr_data_done <= 1;
                @(posedge clk);
                write_one_outbuf_addr_data_done <= 0;
            end   
            process_4_finish <= 1;
        end
        @(posedge clk);
    end    
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_start_run_flag <= 0; 
        write_start_count <= 0;
    end
    else begin
        if (write_start_count >= 8) begin
            write_start_run_flag <= 0; 
        end
        else if (TRAN_AXILiteS_write_start_in === 1) begin
            write_start_run_flag <= 1; 
        end
        if (AESL_write_start_finish === 1) begin
            write_start_count <= write_start_count + 1;
            write_start_run_flag <= 0; 
        end
    end
end

initial begin : write_start
    reg [DATA_WIDTH - 1 : 0] write_start_tmp;
    integer process_num;
    integer write_start_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 5;
    while (1) begin
        process_5_finish = 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (write_start_run_flag === 1) begin
                process_busy = 1;
                write_start_tmp=0;
                write_start_tmp[0 : 0] = 1;
                write (START_ADDR, write_start_tmp, write_start_resp);
                process_busy = 0;
                AESL_write_start_finish <= 1;
                @(posedge clk);
                AESL_write_start_finish <= 0;
            end
            process_5_finish <= 1;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        memptr_read_data_finish <= 0;
        read_memptr_run_flag <= 0; 
        read_memptr_count = 0;
    end
    else begin
        if (AESL_done_index_reg === 1) begin
            read_memptr_run_flag = 1; 
        end
        if (TRAN_AXILiteS_transaction_done_in === 1) begin
            memptr_read_data_finish <= 0;
            read_memptr_count = 0; 
        end
        if (read_one_memptr_data_done === 1) begin
            read_memptr_count = read_memptr_count + 1;
            if (read_memptr_count == memptr_OPERATE_DEPTH) begin
                read_memptr_run_flag <= 0; 
                memptr_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_memptr
    integer read_memptr_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = memptr_c_bitwidth;
    process_num = 6;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_6_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_memptr_run_flag === 1) begin
                process_busy = 1;
                get_vld = 1;
                if (get_vld == 1) begin
                    //read memptr data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (memptr_data_out_addr + read_memptr_count * four_byte_num * 4 + i * 4, RDATA_reg, read_memptr_resp);
                        if (memptr_c_bitwidth < 32) begin
                            mem_memptr[read_memptr_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < memptr_c_bitwidth) begin
                                    mem_memptr[read_memptr_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_memptr_data_done <= 1;
                    @(posedge clk);
                    read_one_memptr_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_6_finish <= 1;
        end
        @(posedge clk);
    end    
end
//------------------------Task and function-------------- 
task read_token; 
    input integer fp; 
    output reg [127 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end 
endtask 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_memptr_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [memptr_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (memptr_c_bitwidth , factor);
  fp = $fopen(`TV_IN_memptr ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_memptr); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < memptr_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_memptr [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_memptr [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_memptr [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_memptr [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_memptr [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_memptr_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [memptr_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (memptr_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (memptr_read_data_finish !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_memptr, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_memptr); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (memptr_DEPTH - memptr_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_memptr[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_memptr[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_memptr[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_memptr[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_memptr[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_memptr[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_memptr[i]);
          end
      end 
      if (factor == 4) begin
          if ((memptr_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][23:16]);
          end
          if ((memptr_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][15:8]);
          end
          if ((memptr_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((memptr_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_memptr[memptr_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
      while (TRAN_AXILiteS_start_in !== 1) begin
          @(posedge clk);
      end
  end 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_mode_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [mode_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (mode_c_bitwidth , factor);
  fp = $fopen(`TV_IN_mode ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_mode); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < mode_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_mode [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_mode [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_mode [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_mode [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_mode [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_inbuf_addr_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [inbuf_addr_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (inbuf_addr_c_bitwidth , factor);
  fp = $fopen(`TV_IN_inbuf_addr ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_inbuf_addr); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < inbuf_addr_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_inbuf_addr [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_inbuf_addr [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_inbuf_addr [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_inbuf_addr [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_inbuf_addr [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_outbuf_addr_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [outbuf_addr_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (outbuf_addr_c_bitwidth , factor);
  fp = $fopen(`TV_IN_outbuf_addr ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_outbuf_addr); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < outbuf_addr_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_outbuf_addr [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_outbuf_addr [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_outbuf_addr [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_outbuf_addr [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_outbuf_addr [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
endmodule
