# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.4
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XAes256cbc" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_AXILITES_BASEADDR" \
        "C_S_AXI_AXILITES_HIGHADDR" \
        "C_S_AXI_P0_BASEADDR" \
        "C_S_AXI_P0_HIGHADDR"

    xdefine_config_file $drv_handle "xaes256cbc_g.c" "XAes256cbc" \
        "DEVICE_ID" \
        "C_S_AXI_AXILITES_BASEADDR" \
        "C_S_AXI_P0_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XAes256cbc" \
        "DEVICE_ID" \
        "C_S_AXI_AXILITES_BASEADDR" \
        "C_S_AXI_AXILITES_HIGHADDR" \
        "C_S_AXI_P0_BASEADDR" \
        "C_S_AXI_P0_HIGHADDR"
}

