// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x0 : Control signals
//       bit 0  - ap_start (Read/Write/COH)
//       bit 1  - ap_done (Read/COR)
//       bit 2  - ap_idle (Read)
//       bit 3  - ap_ready (Read)
//       bit 7  - auto_restart (Read/Write)
//       others - reserved
// 0x4 : Global Interrupt Enable Register
//       bit 0  - Global Interrupt Enable (Read/Write)
//       others - reserved
// 0x8 : IP Interrupt Enable Register (Read/Write)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// 0xc : IP Interrupt Status Register (Read/TOW)
//       bit 0  - Channel 0 (ap_done)
//       bit 1  - Channel 1 (ap_ready)
//       others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAES256CBC_AXILITES_ADDR_AP_CTRL 0x0
#define XAES256CBC_AXILITES_ADDR_GIE     0x4
#define XAES256CBC_AXILITES_ADDR_IER     0x8
#define XAES256CBC_AXILITES_ADDR_ISR     0xc

// p0
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of mode
//        bit 2~0 - mode[2:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of inbuf_addr
//        bit 31~0 - inbuf_addr[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of outbuf_addr
//        bit 31~0 - outbuf_addr[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XAES256CBC_P0_ADDR_MODE_DATA        0x10
#define XAES256CBC_P0_BITS_MODE_DATA        3
#define XAES256CBC_P0_ADDR_INBUF_ADDR_DATA  0x18
#define XAES256CBC_P0_BITS_INBUF_ADDR_DATA  32
#define XAES256CBC_P0_ADDR_OUTBUF_ADDR_DATA 0x20
#define XAES256CBC_P0_BITS_OUTBUF_ADDR_DATA 32

