// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaes256cbc.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAes256cbc_CfgInitialize(XAes256cbc *InstancePtr, XAes256cbc_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAes256cbc_Start(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL) & 0x80;
    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAes256cbc_IsDone(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAes256cbc_IsIdle(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAes256cbc_IsReady(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAes256cbc_EnableAutoRestart(XAes256cbc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XAes256cbc_DisableAutoRestart(XAes256cbc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_AP_CTRL, 0);
}

void XAes256cbc_Set_mode(XAes256cbc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_MODE_DATA, Data);
}

u32 XAes256cbc_Get_mode(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_MODE_DATA);
    return Data;
}

void XAes256cbc_Set_inbuf_addr(XAes256cbc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_INBUF_ADDR_DATA, Data);
}

u32 XAes256cbc_Get_inbuf_addr(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_INBUF_ADDR_DATA);
    return Data;
}

void XAes256cbc_Set_outbuf_addr(XAes256cbc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_OUTBUF_ADDR_DATA, Data);
}

u32 XAes256cbc_Get_outbuf_addr(XAes256cbc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_OUTBUF_ADDR_DATA);
    return Data;
}

u32 XAes256cbc_Get_memptr_BaseAddress(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XAES256CBC_AXILITES_ADDR_MEMPTR_BASE);
}

u32 XAes256cbc_Get_memptr_HighAddress(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XAES256CBC_AXILITES_ADDR_MEMPTR_HIGH);
}

u32 XAes256cbc_Get_memptr_TotalBytes(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XAES256CBC_AXILITES_ADDR_MEMPTR_HIGH - XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + 1);
}

u32 XAes256cbc_Get_memptr_BitWidth(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAES256CBC_AXILITES_WIDTH_MEMPTR;
}

u32 XAes256cbc_Get_memptr_Depth(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAES256CBC_AXILITES_DEPTH_MEMPTR;
}

u32 XAes256cbc_Write_memptr_Words(XAes256cbc *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XAES256CBC_AXILITES_ADDR_MEMPTR_HIGH - XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XAes256cbc_Read_memptr_Words(XAes256cbc *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XAES256CBC_AXILITES_ADDR_MEMPTR_HIGH - XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + (offset + i)*4);
    }
    return length;
}

u32 XAes256cbc_Write_memptr_Bytes(XAes256cbc *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XAES256CBC_AXILITES_ADDR_MEMPTR_HIGH - XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XAes256cbc_Read_memptr_Bytes(XAes256cbc *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XAES256CBC_AXILITES_ADDR_MEMPTR_HIGH - XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XAES256CBC_AXILITES_ADDR_MEMPTR_BASE + offset + i);
    }
    return length;
}

void XAes256cbc_InterruptGlobalEnable(XAes256cbc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_GIE, 1);
}

void XAes256cbc_InterruptGlobalDisable(XAes256cbc *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_GIE, 0);
}

void XAes256cbc_InterruptEnable(XAes256cbc *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_IER);
    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_IER, Register | Mask);
}

void XAes256cbc_InterruptDisable(XAes256cbc *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_IER);
    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_IER, Register & (~Mask));
}

void XAes256cbc_InterruptClear(XAes256cbc *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAes256cbc_WriteReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_ISR, Mask);
}

u32 XAes256cbc_InterruptGetEnabled(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_IER);
}

u32 XAes256cbc_InterruptGetStatus(XAes256cbc *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAes256cbc_ReadReg(InstancePtr->Axilites_BaseAddress, XAES256CBC_AXILITES_ADDR_ISR);
}

